safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache', '_data/google-id.json']
sass:
  style: uncompressed
kramdown:
  toc_levels: "2,3"

plugins:
  - jekyll-assets
  
url: https://users.cs.fiu.edu
baseurl: /~afanasyev/classes/spring21/CNT-4713

# Configuration for permalink
permalink: /:title.html

# Configuration for site
title: "CNT-4713: Net Centric Computing (Computer Network Fundamentals) - Spring 2021 (FIU)"
description:
author: Alex Afanasyev
email:

spreadsheets:
  google_client_id: _data/google-id.json
  spreadsheet:
    - "1397f3YaaZdahOYknY_UEXx5fxaPw85cYf2H8wS1znHw"
  
# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Due Dates
  link: /syllabus.html
- name: Weekly Schedule
  link: /schedule.html
- name: Homeworks
  link: /homeworks.html
- name: Project 1 (Accio)
  link: /project-1.html
- name: Project 2 (Confundo)
  link: /project-2.html
- name: Project 3 (Riddikulus)
  link: /project-3.html

course_info:
  times: 
  room: 
  name: Alex Afanasyev
  contact: aa at cs.fiu.edu
  office_hours: by appointment; as scheduled (some Saturdays 6pm)

  homeworks:
    - deadline: Week 2
    - deadline: Week 3
    - deadline: Week 4
    - deadline: Week 6
    - deadline: Week 8
    - deadline: Week 10
    - deadline: Week 12
    - deadline: Week 14

  midterm: Week 9

  final: Week 15
  final_room: 

  projects:
    - deadline: Weeks 3 (part 1), 4 (part 2), 5 (final part)
    - deadline: Week 7 (part 1), 8 (part 2), 10 (final part)
    - deadline: Week 13 (part 1), 14 (part 2), 15 (final part)

assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/misc

  plugins:
    css:
      autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

    img: { optim: {}, magick: {} }
